#! /bin/sh
# cdda2flac - Zdeněk Janeček. Inspired by J. Schilling
#
# Script for processing all audio tracks with a flac encoder.

# specify the sampling program and its options
# do not specify the track option here!
CDDA2WAV=cdda2wav
CDDA2WAV_OPTS=''
CDDA2WAV_XOPTS=''

# for normal use, comment out the next line
#DEBUG='-d1'

# the post processor is fed through a pipe to avoid space waste
# specify the post processing program and its options
MP_CODER=flac
MP_CODER_HELP=--help
MP_OPTIONS=''
MP_XOPTS=''

found_fileprefix=FALSE

$MP_CODER $MP_CODER_HELP > /dev/null 2> /dev/null
if [ $? != 0 ] ; then
	echo '"'$MP_CODER'"' "not found. Install vorbis-tools first!"
	exit 1
fi

usage() {
	echo "Usage: cdda2flac [dev=<SCSI-address>] [cdda2wav options] [<name prefix for all flac files>] [flac options]"
}

while [ $# -gt 0 ]; do
	case "$1" in
	-help)
		usage
		exit 0
		;;

	dev=*)
		CDDA2WAV_DEV="$1"
		shift
		;;

	-*)
		if [ $found_fileprefix = TRUE ]; then
			MP_XOPTS="$MP_XOPTS $1"
		else
			CDDA2WAV_XOPTS="$CDDA2WAV_XOPTS $1"
		fi
		shift
		;;

	*)
		if [ $found_fileprefix = TRUE ]; then
			echo "Too many file type args."
			usage
			exit 1
		fi
		FILEPREFIX=${1-audiotrack}
		found_fileprefix=TRUE
		#echo "arg:  $1"
		#echo "args: $@"
		shift
		;;
	esac
done

$CDDA2WAV $CDDA2WAV_DEV -H -J -N &> info
COUNT=`cat info | grep 'total tracks:' | cut -c 33-34`
cat info | grep '^Track ..:' | cut -c 12- - | rev | cut -b 2- | rev > names
rm info

for NUMBER in `seq 1 $COUNT` ; do
    NAME=`cat names | sed $NUMBER'!d'`
    if [ $found_fileprefix = TRUE ]; then
        NAME=${NUMBER}_$NAME-$FILEPREFIX.flac
    else
        NAME=${NUMBER}_$NAME.flac
    fi
	
	$CDDA2WAV $CDDA2WAV_DEV $CDDA2WAV_OPTS -t$NUMBER $DEBUG $CDDA2WAV_XOPTS -Owav - | \
	$MP_CODER $MP_OPTIONS $MP_XOPTS - > $NAME
    
	# check result code
	RES=$?
	if [ $RES = 0 ] ; then
		echo File '"'$NAME'"' finished successfully.
	else
		echo File '"'$NAME'"' failed \(result $RES\). Aborted. >&2
		break
	fi
done
